import {
  ArrowDownToLine, ArrowLeft, ArrowRight, ArrowUpFromLine,
  Bell, CalendarCheck, CalendarDays, CalendarPlus, Check, CheckCheck, CircleCheck,
  ClipboardList, Clock, Copy, CreditCard, Crop, ExternalLink, Eye, FileText,
  Link, LogIn, LogOut, Mail, MessageSquare, Pencil, Plus,
  Palette, Printer, RefreshCw, Replace, RotateCcw, Save, Search, Send, Settings,
  Share2, ShieldCheck, ShoppingBag, SlidersHorizontal,
  Trash2, Truck, Unlink, UserPlus, UserRound, X
} from 'lucide-react';

/** Icons describe explicit action keys, never text labels or page-specific classes. */
export const BUTTON_ACTION_ICONS = Object.freeze({
  save: Save,
  add: Plus,
  create: Plus,
  addClient: UserPlus,
  connect: Link,
  link: Link,
  reconnect: Link,
  disconnect: Unlink,
  apply: Check,
  done: Check,
  adjust: SlidersHorizontal,
  continue: ArrowRight,
  next: ArrowRight,
  start: ArrowRight,
  submit: Send,
  send: Send,
  view: Eye,
  open: ExternalLink,
  openFile: FileText,
  edit: Pencil,
  replace: Replace,
  crop: Crop,
  color: Palette,
  profile: UserRound,
  chat: MessageSquare,
  back: ArrowLeft,
  close: X,
  accept: Check,
  confirm: CircleCheck,
  approve: ShieldCheck,
  markPaid: CreditCard,
  pay: CreditCard,
  fulfil: CheckCheck,
  fulfill: CheckCheck,
  ship: Truck,
  waitlist: Clock,
  decline: X,
  cancel: X,
  delete: Trash2,
  remove: Trash2,
  withdraw: RotateCcw,
  download: ArrowDownToLine,
  export: ArrowDownToLine,
  upload: ArrowUpFromLine,
  publish: ArrowUpFromLine,
  import: ArrowUpFromLine,
  share: Share2,
  copy: Copy,
  refresh: RefreshCw,
  retry: RefreshCw,
  reset: RotateCcw,
  sync: RefreshCw,
  search: Search,
  filter: SlidersHorizontal,
  chooseMetric: SlidersHorizontal,
  quickActions: SlidersHorizontal,
  clear: RotateCcw,
  print: Printer,
  settings: Settings,
  signIn: LogIn,
  signOut: LogOut,
  book: CalendarPlus,
  reschedule: CalendarDays,
  pickDate: CalendarDays,
  calendar: CalendarDays,
  time: Clock,
  today: CalendarCheck,
  orders: ClipboardList,
  cart: ShoppingBag,
  buy: ShoppingBag,
  addToCart: ShoppingBag,
  email: Mail,
  notify: Bell
});

export function getButtonActionIcon(action) {
  return Object.prototype.hasOwnProperty.call(BUTTON_ACTION_ICONS, action)
    ? BUTTON_ACTION_ICONS[action]
    : null;
}
