import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { respondToReschedule, writeGuardedBooking } from '../functions/rescheduling.js';
const require = createRequire(new URL('../functions/package.json', import.meta.url));
const { initializeApp } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');
const enabled = !!process.env.FIRESTORE_EMULATOR_HOST;
if (enabled) initializeApp({ projectId: 'demo-book-buy' });
test('Firestore transaction protects acceptance, copies and duplicate requests', { skip: !enabled }, async () => {
  const db = getFirestore(); const owner = 'test-owner'; const threadId = 'test-thread';
  const base = 'artifacts/book-and-buy-v1';
  const day = new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10);
  const booking = { id: 'test-booking', serviceId: 'service', serviceName: 'Consultation', clientEmail: 'client@example.test', status: 'confirmed', date: day, dateKey: day, time: '09:00', durationMinutes: 60, revision: 0, paymentStatus: 'paid', amountInCents: 10000 };
  await db.doc(`${base}/users/${owner}/config/settings`).set({ timezone: 'UTC', services: [{ id: 'service', name: 'Consultation', duration: 60 }], bookings: [booking], availabilityRules: { openWeekdays: ['mon','tue','wed','thu','fri','sat','sun'], businessOpenTime: '09:00', businessCloseTime: '17:00' } });
  await db.doc(`${base}/clientThreads/${threadId}`).set({ ownerId: owner, bookingId: booking.id, clientEmail: booking.clientEmail });
  await db.doc(`${base}/users/${owner}/rescheduleProposals/${booking.id}`).delete();
  const client = { uid: 'client', token: { email: booking.clientEmail, email_verified: true } };
  const business = { uid: owner, token: { email: 'owner@example.test', email_verified: true } };
  const proposed = await respondToReschedule({ threadId, action: 'propose', requestId: crypto.randomUUID(), slot: { dateKey: day, time: '11:00' } }, client, db);
  assert.equal(proposed.proposal.status, 'pending');
  assert.equal((await db.doc(`${base}/users/${owner}/config/settings`).get()).data().bookings[0].time, '09:00');
  await assert.rejects(respondToReschedule({ threadId, action: 'accept', expectedRevision: 1, requestId: crypto.randomUUID() }, client, db), /other party/);
  await assert.rejects(respondToReschedule({ threadId, action: 'accept', expectedRevision: 0, requestId: crypto.randomUUID() }, business, db), /changed/);
  const request = { threadId, action: 'accept', expectedRevision: 1, requestId: crypto.randomUUID() };
  const results = await Promise.all([respondToReschedule(request, business, db), respondToReschedule(request, business, db)]);
  assert.equal(results[0].proposal.status, 'accepted');
  const saved = (await db.doc(`${base}/users/${owner}/config/settings`).get()).data().bookings[0];
  assert.equal(saved.time, '11:00'); assert.equal(saved.paymentStatus, 'paid'); assert.equal(saved.amountInCents, 10000);
  assert.equal((await db.doc(`${base}/clientAccess/${booking.clientEmail}/bookings/${booking.id}`).get()).data().time, '11:00');
  await assert.rejects(writeGuardedBooking({ ownerId: owner, booking: { id: booking.id, time: '12:00' }, expectedRevision: 0 }, business, db), /changed/);
  await assert.rejects(respondToReschedule({ threadId, action: 'propose', requestId: crypto.randomUUID(), slot: { dateKey: day, time: '12:00' } }, { uid: 'stranger', token: { email: 'stranger@example.test', email_verified: true } }, db), /cannot change/);
});
