import { createDefaultCommunications } from './communicationsConfig';
import { defaultFaqItems } from './editorConfig';

export const createDefaultSettings = () => ({
  slug: 'your-business',
  brandName: 'Your Business',
  email: '',
  phone: '',
  welcomeMessage: 'Reserve your session.',
  tagline: 'Online bookings',
  primaryColor: '#050505',
  headingColor: '#000000',
  bodyColor: '#666666',
  backgroundColor: '#ffffff',
  slotBgColor: '#F8FAFC',
  slotTextColor: '#000000',
  dateBgColor: 'transparent',
  dateTextColor: '#666666',
  dateActiveBgColor: '#050505',
  dateActiveTextColor: '#ffffff',
  buttonTextColor: '#ffffff',
  fontFamily: 'figtree',
  nativeAccent: true,
  editorPaletteFlowColor: 'blue',
  editorColorDepth: 50,
  editorColorDepths: {},
  editorColorMix: ['blue'],
  headingFontFamily: 'plus-jakarta',
  bodyFontFamily: 'figtree',
  buttonFontFamily: 'inter',
  slotFontFamily: 'plus-jakarta',
  dateFontFamily: 'plus-jakarta',
  brandNameSize: 76,
  brandNameFontFamily: 'plus-jakarta',
  taglineSize: 9,
  taglineFontFamily: 'figtree',
  welcomeSize: 20,
  welcomeFontFamily: 'figtree',
  interfaceStyleDirection: 'native-precision',
  buttonStyle: 'pill',
  availabilityStyle: 'solid',
  dateStyle: 'solid',
  timeSlotStyle: 'solid',
  actionButtonStyle: 'solid',
  calendarDisplayStyle: 'studio',
  timeDisplayStyle: 'pill',
  serviceDisplayStyle: 'rail',
  serviceDropdownEnabled: false,
  serviceBorderStyle: 'solid',
  serviceBgColor: '',
  serviceBorderColor: '',
  serviceTextColor: '',
  serviceBodyColor: '',
  serviceMetaColor: '',
  serviceActiveBgColor: '',
  serviceActiveBorderColor: '',
  serviceHeading: 'Choose your service',
  serviceSubtext: 'Select the option that works best for you.',
  faqStyle: 'minimal',
  faqDisplayStyle: 'accordion',
  faqBgColor: 'transparent',
  faqBorderColor: '#00000020',
  faqTextColor: '',
  faqAnswerColor: '',
  faqFontFamily: '',
  venueGalleryStyle: 'mosaic',
  venueBgColor: '',
  venueBorderColor: '',
  venueTextColor: '',
  venueBodyColor: '',
  venueTitle: 'Inside the space',
  venueIntro: 'See the place before you book.',
  mapDisplayStyle: 'card',
  socialIconStyle: 'outline',
  socialDisplayStyle: 'icons',
  socialIconBgColor: 'transparent',
  socialIconColor: '',
  socialIconTextColor: '',
  socialHeading: 'Stay connected',
  socialSubtext: 'Find us online and keep in touch.',
  cartPageColors: {},
  checkoutPageColors: {},
  successPageColors: {},
  dateLabel: 'Pick your booking date',
  dateSubtext: 'Choose an available day for your booking.',
  timeLabel: 'What time works?',
  timeSubtext: 'Choose the time that suits you best.',
  faqHeading: 'Questions before booking',
  faqSubtext: 'Helpful answers before you confirm.',
  bookingCtaLabel: 'Add booking to cart',
  cartBackLabel: 'Edit selection',
  cartEyebrow: 'Your booking',
  cartTitle: 'Review booking.',
  cartCopy: 'Check your service, date, and time before checkout. You can edit the booking if anything looks off.',
  cartCtaLabel: 'Complete your details',
  checkoutBackLabel: 'Back to cart',
  checkoutEyebrow: 'Checkout',
  checkoutTitle: 'Fill in your details.',
  checkoutCopy: 'Request the booking first. If payment is needed, the next step will take care of it cleanly.',
  checkoutNote: 'The business reviews your request, confirms the slot, and keeps updates in your client portal.',
  checkoutSubmitLabel: 'Request booking',
  checkoutWaitlistLabel: 'Join waitlist',
  checkoutSendingLabel: 'Sending request',
  buttonText: 'Book Now',
  confirmButtonText: 'Confirm Booking',
  detailsHeading: 'Your Details',
  detailsSubHeading: 'Secure Your Slot',
  successStatusLabel: 'Booking Status',
  successHeading: 'Request sent.',
  successCopy: 'We have your request and will review the booking details shortly.',
  successReferenceLabel: 'Reference',
  successReferenceCopy: 'Keep this for updates with the business.',
  successNextLabel: 'Next',
  successNextTitle: 'Business review',
  successNextCopy: 'We will confirm the slot, follow up if needed, or help adjust the booking.',
  successNewRequestLabel: 'New Request',
  availableTimes: ['09:00', '10:30', '12:00', '14:30', '16:00', '17:30'],
  schedule: {},
  staffCalendars: {},
  availabilityRules: {
    enabled: true,
    scheduleMode: 'time_slots',
    staffAssignmentMode: 'auto',
    holdMode: 'pending_confirmed',
    bookingNotice: '',
    maxAdvanceBooking: '',
    cancellationWindow: '',
    reschedulingAllowed: true,
    repeatBookingsAllowed: false
  },
  reminders: { enabled: true, client24h: true, client2h: true },
  googleCalendar: { mode: 'manual-sync', connectedEmail: '', connectedAt: 0, lastSyncedAt: 0, lastSyncCount: 0 },
  features: { birthday: true, waitlist: true, socialProof: true, loadingScreen: true, firstAvailable: true, collectClientName: true, collectClientPhone: true, collectClientEmail: true, collectClientNotes: false, emailUpdates: true, faqEnabled: true, socialLinks: false, location: '', faqs: defaultFaqItems.map(item => ({ ...item })) },
  accountProfiles: {},
  themeTemplates: [],
  serviceIndustry: '',
  services: [],
  logoDisplay: { visible: true, alignment: 'left', size: 96, placement: 'title' },
  bannerDisplay: { visible: true, height: 220, position: 'center', placement: 'hero', opacity: 100 },
  logo: '',
  bannerImage: '',
  venuePhotos: [],
  address: '',
  mapPlace: null,
  socials: { instagram: '', tiktok: '', facebook: '', website: '' },
  socialPlatforms: { instagram: true, tiktok: true, facebook: true, website: true }
});

export const createGuestDemoWorkspace = () => ({
  settings: createDefaultSettings(),
  bookings: [],
  staffList: [{ id: 'owner', name: 'Admin', color: '#39FF14', role: 'owner', status: 'connected' }],
  clientRecords: [],
  communications: createDefaultCommunications()
});
