export const DEFAULT_HOME_SECTION_ORDER = [
  'about',
  'offerIntro',
  'gallery',
  'reviews',
  'faq',
  'map'
];

export const createDefaultHomeSections = () => ({
  about: true,
  gallery: true,
  reviews: true,
  map: true,
  faq: true,
  offerIntro: true,
  reasons: false,
  venue: true,
  offer: false,
  bookStrip: false
});

export const createDefaultHomeSectionOrder = () => [...DEFAULT_HOME_SECTION_ORDER];

export const createDefaultSettings = () => ({
  slug: 'your-business',
  brandName: 'Your Business',
  email: '',
  phone: '',
  welcomeMessage: 'Reserve your session.',
  tagline: 'Book services. Buy products.',
  primaryColor: '#050505',
  headingColor: '#000000',
  bodyColor: '#666666',
  backgroundColor: '#ffffff',
  fontFamily: 'figtree',
  nativeAccent: true,
  headingFontFamily: 'plus-jakarta',
  bodyFontFamily: 'figtree',
  buttonFontFamily: 'figtree',
  brandNameFontFamily: 'plus-jakarta',
  interfaceStyleDirection: 'native-precision',
  website: {
    pages: {
      home: true,
      book: true,
      buy: true
    },
    sections: createDefaultHomeSections(),
    sectionOrder: createDefaultHomeSectionOrder(),
    headline: '',
    subcopy: 'Book a service or buy products from one place.',
    ctaLabel: 'Book',
    buyCtaLabel: 'Buy',
    homeHeadline: '',
    homeSubtext: 'Book a service or buy products from one place.',
    categoryId: '',
    profileCategory: '',
    profileLocation: '',
    venueMode: 'physical',
    locationLat: null,
    locationLng: null,
    countryCode: '',
    region: '',
    city: '',
    servesCountries: [],
    heroImageUrl: '',
    logoUrl: '',
    bookHeadline: 'Book',
    bookSubtext: 'Choose a service and request a time.',
    buyHeadline: 'Buy',
    buySubtext: 'Order products from this business.',
    aboutTitle: 'About us',
    aboutEyebrow: 'About',
    aboutBody: '',
    aboutImageUrl: '',
    visionTitle: 'Our vision',
    visionBody: '',
    visionImageUrl: '',
    missionTitle: 'Our mission',
    missionBody: '',
    missionImageUrl: '',
    aboutPages: [],
    styleTokens: {},
    reasonsTitle: 'What we offer',
    reasonsEyebrow: 'The craft',
    reasonsBody: '',
    reasonsMarkerStyle: 'icon',
    reasons: [],
    venueTitle: 'Photos',
    venueEyebrow: 'Photos',
    venueBody: '',
    venueIcon: 'camera',
    venueImages: [],
    mapTitle: 'Visit',
    mapEyebrow: 'Find us',
    mapBody: '',
    mapIcon: 'location',
    address: '',
    mapEmbedUrl: '',
    mapLinkUrl: '',
    googlePlaceId: '',
    googleReviewsEnabled: null,
    googleReviewsSyncedAt: '',
    reviewsTitle: 'Reviews',
    reviewsEyebrow: 'Reviews',
    reviewsBody: '',
    reviewsIcon: 'star',
    reviews: [],
    offerTitle: 'View what we offer',
    offerBookCta: 'Bookings',
    offerBuyCta: 'Products',
    bookStripTitle: 'Ready to book?',
    bookStripBody: 'Pick a service and request a time that works for you.',
    bookStripCta: 'See availability',
    bookFaqTitle: 'FAQ',
    bookFaqEyebrow: 'FAQ',
    bookFaqBody: '',
    bookFaqIcon: 'question',
    bookFaq: []
  },
  services: [],
  serviceCategories: [],
  products: [],
  productCategories: [],
  currency: 'R',
  timezone: 'Africa/Johannesburg',
  planId: 'starter',
  billingInterval: 'month',
  planStatus: 'trialing',
  trialEndsAt: null,
  policies: {
    cancellation: '',
    terms: '',
    privacy: ''
  },
  features: {
    waitlist: true,
    faqEnabled: true,
    collectClientName: true,
    collectClientPhone: true,
    collectClientEmail: true,
    collectClientNotes: true
  }
});

export { createDemoWorkspace as createDemoWorkspaceSettings } from '../data/demoWorkspace';
